# Use uma imagem base do Python
FROM python:3.10-slim

# Configurar o diretório de trabalho
WORKDIR /app

# Instalar dependências do sistema necessárias
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    wget \
    unzip && \
    rm -rf /var/lib/apt/lists/*

# Copiar os arquivos de dependência
COPY requirements.txt .

# Instalar as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o modelo Vosk manualmente baixado
COPY models/vosk-model-small-pt /app/models/vosk-model-small-pt

# Copiar o restante do código para dentro do container
COPY . .

# Expor a porta para a aplicação
EXPOSE 5000

# Comando para iniciar o servidor Flask com Gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
